/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package aryan.sai.atm;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Student
 */
public class withdraw extends javax.swing.JFrame {

    /**
     * Creates new form withdraw
     */
    String acno;

    public withdraw(String acno) {
        this.acno = acno;
        initComponents();

    }

    private withdraw() {
        //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        WithdrawAmt = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        BWithdrw = new javax.swing.JButton();
        BHome = new javax.swing.JButton();
        BReceipt = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        BillArea = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Withdrawl Amount");

        BWithdrw.setText("Withdraw");
        BWithdrw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BWithdrwActionPerformed(evt);
            }
        });

        BHome.setText("Home");
        BHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BHomeActionPerformed(evt);
            }
        });

        BReceipt.setText("Receipt");
        BReceipt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BReceiptActionPerformed(evt);
            }
        });

        BillArea.setColumns(20);
        BillArea.setRows(5);
        BillArea.setText("             Hii Customer!!!!\n  Your previous transaction details are");
        jScrollPane1.setViewportView(BillArea);

        jLabel2.setText(" Your Receipt:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Want some Money??");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1)
                .addGap(8, 8, 8))
            .addGroup(layout.createSequentialGroup()
                .addGap(175, 175, 175)
                .addComponent(BReceipt)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(WithdrawAmt, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BWithdrw, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(125, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BHome)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BHome)
                    .addComponent(jLabel3))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(WithdrawAmt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BWithdrw, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(BReceipt)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(96, 96, 96))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BWithdrwActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BWithdrwActionPerformed
        // TODO add your handling code here:

        int amt = Integer.parseInt(WithdrawAmt.getText());
        int balnc = 0;
        int newb = balnc - amt;
        int count = 0;
        if (amt < 15000) {
            Connection con;
            try {
                Class.forName("com.mysql.jdbc.Driver");
                con = DriverManager.getConnection("jdbc:mysql://localhost:3306/atm", "root", "sairam");
                Statement sai = con.createStatement();
                ResultSet r = sai.executeQuery("select count(tranno) from transaction where acno='" + acno + "' group by dot,acno,type");
                while (r.next()) {
                    count = r.getInt("count(tranno)");
                }
                if (count >= 3) {
                    JOptionPane.showMessageDialog(this, "Sorry you can't withdraw more than thrice a day");
                } else {
                    Statement s = con.createStatement();
                    ResultSet rs = s.executeQuery("select openbalnc from register where acno='" + acno + "'");
                    while (rs.next()) {
                        balnc = rs.getInt("openbalnc");
                    }
                    if (balnc == 0) {
                        JOptionPane.showMessageDialog(this, "Sorry there is no money in your Account");
                    }

                    if (balnc > amt) {
                        newb = balnc - amt;
                        Statement st = con.createStatement();
                        st.executeUpdate("Insert into transaction(acno,dot,tramt,balnc,oldbal,type) values('" + acno + "',curdate()," + amt + "," + newb + "," + balnc + ",'Withdraw')");
                        Statement sa = con.createStatement();
                        sa.executeUpdate("Update register set openbalnc=" + newb + " where acno='" + acno + "'");
                        JOptionPane.showMessageDialog(this, "Successful");
                    } else {
                        JOptionPane.showMessageDialog(this, "The amount you have entered is more than your balance/n Please Re-enter");
                    }
                }
            } catch (ClassNotFoundException | SQLException ex) {
                Logger.getLogger(Register.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            JOptionPane.showMessageDialog(this, " Sorry withdrawl amount should not be more than 15000");
        }
    }//GEN-LAST:event_BWithdrwActionPerformed
    private void BHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BHomeActionPerformed
        // TODO add your handling code here:
        ATM_main main = new ATM_main();
        main.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BHomeActionPerformed

    private void BReceiptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BReceiptActionPerformed
        // TODO add your handling code here:
        Connection con;
        String name = null, balnc = null, tranno = null, type = null, tramt = null;
        try {
            Class.forName("com.mysql.jdbc.Driver");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ATM_main.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/atm", "root", "sairam");
            Statement st;
            st = con.createStatement();
            ResultSet rs = st.executeQuery("Select * from register join transaction where register.acno='" + acno + "' and register.acno=transaction.acno;");
            while (rs.next()) {
                tranno = rs.getString("tranno");
                name = rs.getString("name");
                tramt = rs.getString("tramt");
                type = rs.getString("type");
                balnc = rs.getString("balnc");

            }
            BillArea.append("\n Transaction Number =" + tranno + "\n A/C no. =" + acno + "\n Transaction Amount =" + tramt + "\n Type of Transaction =" + type + "\n Balance in your A/C is " + balnc);


        } catch (SQLException ex) {
            Logger.getLogger(ATM_main.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_BReceiptActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(withdraw.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(withdraw.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(withdraw.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(withdraw.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BHome;
    private javax.swing.JButton BReceipt;
    private javax.swing.JButton BWithdrw;
    private javax.swing.JTextArea BillArea;
    private javax.swing.JTextField WithdrawAmt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
